#!/usr/bin/env python3
"""Autonomous software factory MVP.

This script converts a high-level goal (for example, "build a customer support portal") into:
1) A structured requirements specification
2) An architecture decision record
3) A phased execution plan/backlog
4) A starter project scaffold

The implementation is intentionally deterministic and lightweight so it can be
used as a practical first step toward a larger agentic system.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from config.local_llm_client import (  # noqa: E402
    derive_local_llm_focus,
    generate_local_llm_advice,
    render_local_llm_advice,
    render_local_llm_focus,
)


DEFAULT_SGA_ENTITIES = [
    "Student",
    "Professor",
    "Course",
    "Enrollment",
    "Grade",
    "Attendance",
    "AcademicPeriod",
]

DEFAULT_SGA_MODULES = [
    "authentication",
    "student_management",
    "course_catalog",
    "enrollment",
    "grading",
    "attendance",
    "reports",
]

DEFAULT_SGA_WORKFLOWS = [
    "Student enrollment lifecycle",
    "Course assignment by professor",
    "Grade publishing and transcript generation",
    "Attendance tracking and alerts",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a deterministic autonomous-build blueprint and scaffold."
    )
    parser.add_argument(
        "--goal",
        required=True,
        help="High-level command (example: 'build a customer support portal').",
    )
    parser.add_argument(
        "--project-name",
        help="Optional project slug. If omitted, it is derived from goal.",
    )
    parser.add_argument(
        "--output",
        default="generated",
        help="Output root folder (default: generated).",
    )
    parser.add_argument(
        "--constraint",
        action="append",
        default=[],
        help=(
            "Constraint key=value pair. Repeat this flag for multiple constraints. "
            "Examples: --constraint users=15000 --constraint cloud=aws"
        ),
    )
    parser.add_argument(
        "--interactive",
        action="store_true",
        help="Ask guided questions to fill missing constraints before generation.",
    )
    parser.add_argument(
        "--dry-run-execution",
        action="store_true",
        help="Generate a phase-by-phase execution report without performing destructive actions.",
    )
    parser.add_argument(
        "--advance-phase",
        action="store_true",
        help="Advance the execution state by one step and persist the updated state.",
    )
    parser.add_argument(
        "--execute-phase",
        action="store_true",
        help="Execute tasks for the active phase and persist evidence and audit trail.",
    )
    parser.add_argument(
        "--dry-run-actions",
        action="store_true",
        help="Preview phase task execution without changing files or task statuses.",
    )
    parser.add_argument(
        "--rollback-last-task",
        action="store_true",
        help="Rollback the most recently completed task using the execution audit trail.",
    )
    parser.add_argument(
        "--verify-decision-log",
        action="store_true",
        help="Verify decision-log.json integrity using embedded hash and checksum file.",
    )
    parser.add_argument(
        "--state-file",
        help="Optional execution state file path. Defaults to execution/state.json inside the project.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite if destination already exists.",
    )
    return parser.parse_args()


def recommend_default_local_llm_config() -> dict[str, Any] | None:
    try:
        from config.recommend_local_model import detect_hardware, rank_models
    except Exception:
        return None

    hardware = detect_hardware()
    ranked = rank_models(hardware)
    if not ranked:
        return None

    recommended = ranked[0]["model"]
    return {
        "provider": "ollama",
        "model": recommended.name,
        "temperature": 0.2,
        "context_window": 8192,
        "max_retries": 2,
        "fallback_mode": "deterministic",
        "autogenerated": True,
        "autogenerated_reason": "hardware-based first-run recommendation",
    }


def ensure_local_llm_config(
    repo_root: Path,
    config_override: dict[str, Any] | None = None,
) -> bool:
    config_path = repo_root / "config" / "local_llm.json"
    if config_path.exists():
        return False

    payload = config_override or recommend_default_local_llm_config()
    if payload is None:
        return False

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8",
    )
    return True


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "autonomous-project"


def infer_domain(goal: str) -> str:
    normalized = goal.lower()
    sga_keywords = [
        "sga",
        "academic",
        "gerenciamento academico",
        "sistema academico",
        "school",
        "university",
    ]
    if any(keyword in normalized for keyword in sga_keywords):
        return "academic_management"
    return "generic_web_application"


def parse_constraints(raw_constraints: list[str]) -> dict[str, Any]:
    constraints: dict[str, Any] = {}
    for item in raw_constraints:
        if "=" not in item:
            raise ValueError(
                f"Invalid constraint '{item}'. Expected key=value format."
            )
        key, value = item.split("=", 1)
        key = key.strip().lower()
        value = value.strip()
        if not key:
            raise ValueError(f"Invalid constraint '{item}'. Empty key is not allowed.")
        constraints[key] = coerce_constraint_value(key, value)
    return constraints


def append_decision(
    decision_entries: list[dict[str, Any]],
    key: str,
    value: Any,
    source: str,
    note: str | None = None,
) -> None:
    entry = {
        "key": key,
        "value": value,
        "source": source,
    }
    if note:
        entry["note"] = note
    decision_entries.append(entry)


def read_input(prompt: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    try:
        value = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        return default or ""
    if value:
        return value
    return default or ""


def read_int(prompt: str, default: int) -> int:
    while True:
        value = read_input(prompt, str(default))
        try:
            return int(value)
        except ValueError:
            print("Please enter a valid integer value.", file=sys.stderr)


def read_choice(prompt: str, options: list[str], default: str) -> str:
    normalized = [option.lower() for option in options]
    while True:
        value = read_input(f"{prompt} ({'/'.join(options)})", default).lower()
        if value in normalized:
            return value
        print(f"Please choose one of: {', '.join(options)}", file=sys.stderr)


def read_csv(prompt: str, default: list[str] | None = None) -> list[str]:
    default_text = ",".join(default or [])
    value = read_input(prompt, default_text)
    return [item.strip() for item in value.split(",") if item.strip()]


def prompt_project_name_interactively(
    project_name: str,
    decision_entries: list[dict[str, Any]] | None = None,
) -> str:
    suggested = project_name or "autonomous-project"
    chosen_name = read_input("Project name", suggested)
    normalized_name = slugify(chosen_name)
    if decision_entries is not None:
        append_decision(
            decision_entries,
            key="project_name",
            value=normalized_name,
            source="interactive",
            note="Provided through interactive interview.",
        )
    return normalized_name


def collect_constraints_interactively(
    constraints: dict[str, Any],
    domain: str,
    decision_entries: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    interactive_constraints = dict(constraints)
    print("Interactive mode enabled. Press Enter to accept defaults.")

    if "users" not in interactive_constraints and "max_users" not in interactive_constraints:
        interactive_constraints["users"] = read_int("Estimated users", 3000)
        if decision_entries is not None:
            append_decision(
                decision_entries,
                key="users",
                value=interactive_constraints["users"],
                source="interactive",
            )

    if "cloud" not in interactive_constraints:
        interactive_constraints["cloud"] = read_input("Cloud provider", "agnostic")
        if decision_entries is not None:
            append_decision(
                decision_entries,
                key="cloud",
                value=interactive_constraints["cloud"],
                source="interactive",
            )

    if "budget" not in interactive_constraints:
        interactive_constraints["budget"] = read_choice(
            "Budget profile", ["low", "medium", "high"], "medium"
        )
        if decision_entries is not None:
            append_decision(
                decision_entries,
                key="budget",
                value=interactive_constraints["budget"],
                source="interactive",
            )

    if "compliance" not in interactive_constraints and "regulations" not in interactive_constraints:
        default_compliance = ["LGPD"] if domain == "academic_management" else []
        compliance = read_csv(
            "Compliance regulations (comma separated)", default_compliance
        )
        if compliance:
            interactive_constraints["compliance"] = compliance
            if decision_entries is not None:
                append_decision(
                    decision_entries,
                    key="compliance",
                    value=interactive_constraints["compliance"],
                    source="interactive",
                )

    if domain == "academic_management" and "delivery" not in interactive_constraints:
        interactive_constraints["delivery"] = read_choice(
            "Primary delivery channel", ["web", "mobile", "hybrid"], "web"
        )
        if decision_entries is not None:
            append_decision(
                decision_entries,
                key="delivery",
                value=interactive_constraints["delivery"],
                source="interactive",
            )

    return interactive_constraints


def coerce_constraint_value(key: str, value: str) -> Any:
    if key in {"users", "max_users"}:
        try:
            return int(value)
        except ValueError as exc:
            raise ValueError(f"Constraint '{key}' expects an integer value.") from exc
    if key in {"compliance", "regulations"}:
        return [item.strip() for item in value.split(",") if item.strip()]
    return value


def choose_architecture(constraints: dict[str, Any], domain: str) -> dict[str, Any]:
    users = int(constraints.get("users", constraints.get("max_users", 3000)))
    cloud = str(constraints.get("cloud", "agnostic"))
    budget = str(constraints.get("budget", "medium")).lower()

    if users >= 50000:
        style = "microservices + event-driven"
        rationale = [
            "High user volume favors independent scaling and fault isolation.",
            "Event-driven workflows reduce coupling between core modules.",
        ]
    elif users >= 10000:
        style = "modular monolith + async workers"
        rationale = [
            "Large but manageable volume balances simplicity and scalability.",
            "Modules can be extracted into services later with low migration risk.",
        ]
    else:
        style = "modular monolith"
        rationale = [
            "Fastest path to value for small and medium institutions.",
            "Operational complexity stays low while keeping clear module boundaries.",
        ]

    database = "PostgreSQL"
    if budget == "low":
        deployment = "single region, container-based deployment"
    else:
        deployment = "multi-environment deployment with staging and production"

    if domain == "academic_management":
        backend = "Python API with role-based access control"
    else:
        backend = "Python API"

    return {
        "style": style,
        "backend": backend,
        "frontend": "Web dashboard",
        "database": database,
        "deployment": deployment,
        "cloud": cloud,
        "rationale": rationale,
    }


def build_spec(goal: str, domain: str, constraints: dict[str, Any]) -> dict[str, Any]:
    if domain == "academic_management":
        entities = DEFAULT_SGA_ENTITIES
        modules = DEFAULT_SGA_MODULES
        workflows = DEFAULT_SGA_WORKFLOWS
        assumptions = [
            "Primary interface is web.",
            "Role model includes admin, professor, and student.",
            "System must support auditability for academic records.",
        ]
        non_functional = {
            "availability": "99.9%",
            "api_p95_latency": "< 300ms",
            "security": [
                "RBAC",
                "input validation",
                "audit logs",
            ],
        }
    else:
        entities = ["User", "Resource", "AuditEvent"]
        modules = ["authentication", "core_domain", "reporting"]
        workflows = ["Create and manage resources", "Track user actions"]
        assumptions = [
            "Web-based delivery.",
            "Relational persistence.",
        ]
        non_functional = {
            "availability": "99.5%",
            "api_p95_latency": "< 400ms",
            "security": ["RBAC", "audit logs"],
        }

    governance = {
        "approval_gates": [
            "Production deployment",
            "Destructive database migrations",
            "Permission model changes",
        ],
        "mandatory_checks": [
            "Unit tests",
            "Static analysis",
            "Dependency vulnerability scan",
        ],
    }

    return {
        "goal": goal,
        "domain": domain,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "constraints": constraints,
        "assumptions": assumptions,
        "entities": entities,
        "modules": modules,
        "workflows": workflows,
        "non_functional": non_functional,
        "governance": governance,
    }


def build_backlog(spec: dict[str, Any], architecture: dict[str, Any]) -> list[dict[str, Any]]:
    modules = spec["modules"]
    module_tasks = [f"Implement module: {module}" for module in modules]

    return [
        {
            "phase": "P0 - Formalize requirements",
            "tasks": [
                "Validate goal against domain ontology",
                "Resolve missing constraints and assumptions",
                "Freeze machine-readable specification",
            ],
            "exit_criteria": [
                "requirements.json approved",
                "Risk list reviewed",
            ],
        },
        {
            "phase": "P1 - Architecture baseline",
            "tasks": [
                f"Adopt architecture style: {architecture['style']}",
                "Define API contract and database schema",
                "Set CI quality gates",
            ],
            "exit_criteria": [
                "ADR accepted",
                "Schema reviewed",
            ],
        },
        {
            "phase": "P2 - Build core modules",
            "tasks": module_tasks,
            "exit_criteria": [
                "Smoke tests passing",
                "No high-severity static analysis issues",
            ],
        },
        {
            "phase": "P3 - Validation and hardening",
            "tasks": [
                "Run integration scenarios",
                "Validate security controls",
                "Execute rollback drill in staging",
            ],
            "exit_criteria": [
                "All critical scenarios pass",
                "Release gate approved",
            ],
        },
    ]


def build_execution_report(
    spec: dict[str, Any], architecture: dict[str, Any], backlog: list[dict[str, Any]]
) -> dict[str, Any]:
    phases = []
    completed_modules = []

    for phase_index, phase in enumerate(backlog, start=1):
        if phase["phase"].startswith("P0"):
            status = "ready"
        elif phase["phase"].startswith("P1"):
            status = "blocked-until-spec-approved"
        elif phase["phase"].startswith("P2"):
            status = "blocked-until-architecture-baselined"
        else:
            status = "blocked-until-tests-pass"

        phase_modules = [
            task.removeprefix("Implement module: ")
            for task in phase["tasks"]
            if task.startswith("Implement module: ")
        ]
        completed_modules.extend(phase_modules)

        phases.append(
            {
                "order": phase_index,
                "name": phase["phase"],
                "status": status,
                "tasks": phase["tasks"],
                "exit_criteria": phase["exit_criteria"],
                "modules": phase_modules,
            }
        )

    return {
        "goal": spec["goal"],
        "domain": spec["domain"],
        "selected_architecture": architecture,
        "phase_summary": phases,
        "module_coverage": {
            "planned_modules": spec["modules"],
            "included_in_phases": completed_modules,
        },
        "next_action": "Approve requirements, then implement P2 modules in order.",
    }


def build_decision_log(
    goal: str,
    domain: str,
    project_name: str,
    constraints: dict[str, Any],
    decision_entries: list[dict[str, Any]],
) -> dict[str, Any]:
    normalized_entries = [
        {
            "index": index,
            "key": entry["key"],
            "value": entry["value"],
            "source": entry["source"],
            "note": entry.get("note"),
        }
        for index, entry in enumerate(decision_entries, start=1)
    ]
    return {
        "goal": goal,
        "domain": domain,
        "project_name": project_name,
        "constraints": constraints,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "entries": normalized_entries,
    }


def compute_decision_log_hash(decision_log: dict[str, Any]) -> str:
    canonical = json.dumps(
        decision_log,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def verify_decision_log_integrity(project_root: Path) -> tuple[bool, str]:
    decision_log_path = project_root / "planning" / "decision-log.json"
    checksum_path = project_root / "planning" / "decision-log.sha256"

    if not decision_log_path.exists():
        return False, "missing planning/decision-log.json"
    if not checksum_path.exists():
        return False, "missing planning/decision-log.sha256"

    decision_log = json.loads(decision_log_path.read_text(encoding="utf-8"))
    embedded_integrity = decision_log.get("integrity", {})
    embedded_hash = embedded_integrity.get("hash")
    if not isinstance(embedded_hash, str) or not embedded_hash:
        return False, "decision-log.json has no embedded integrity hash"

    # Recompute hash without the integrity field to match generation flow.
    normalized_payload = dict(decision_log)
    normalized_payload.pop("integrity", None)
    recalculated_hash = compute_decision_log_hash(normalized_payload)

    checksum_line = checksum_path.read_text(encoding="utf-8").strip()
    checksum_parts = checksum_line.split()
    if len(checksum_parts) < 1:
        return False, "invalid checksum file format"
    checksum_hash = checksum_parts[0]

    if embedded_hash != recalculated_hash:
        return False, "embedded hash mismatch in decision-log.json"
    if checksum_hash != recalculated_hash:
        return False, "checksum mismatch in planning/decision-log.sha256"

    return True, "decision log integrity verified"


def build_execution_state(
    spec: dict[str, Any], architecture: dict[str, Any], backlog: list[dict[str, Any]]
) -> dict[str, Any]:
    phases = []
    for phase_index, phase in enumerate(backlog, start=1):
        phase_modules = [
            task.removeprefix("Implement module: ")
            for task in phase["tasks"]
            if task.startswith("Implement module: ")
        ]
        phases.append(
            {
                "order": phase_index,
                "name": phase["phase"],
                "status": "ready" if phase_index == 1 else "pending",
                "tasks": phase["tasks"],
                "task_status": [
                    {
                        "id": f"P{phase_index}-T{task_index}",
                        "title": task,
                        "status": "pending",
                        "last_updated": None,
                        "evidence_file": str(
                            Path("execution")
                            / "evidence"
                            / f"p{phase_index:02d}"
                            / f"t{task_index:02d}-{slugify(task)}.md"
                        ),
                    }
                    for task_index, task in enumerate(phase["tasks"], start=1)
                ],
                "exit_criteria": phase["exit_criteria"],
                "modules": phase_modules,
            }
        )

    return {
        "goal": spec["goal"],
        "domain": spec["domain"],
        "spec_snapshot": spec,
        "selected_architecture": architecture,
        "phase_summary": phases,
        "history": [],
        "audit_trail": [],
        "rolled_back_event_ids": [],
        "last_action": "initialized",
        "last_error": None,
        "last_updated": datetime.now(timezone.utc).isoformat(),
    }


def append_audit_event(
    state: dict[str, Any],
    event_type: str,
    phase_name: str,
    status: str,
    task_title: str | None = None,
    details: dict[str, Any] | None = None,
) -> None:
    audit_trail = state.setdefault("audit_trail", [])
    audit_trail.append(
        {
            "id": len(audit_trail) + 1,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "event_type": event_type,
            "phase": phase_name,
            "task": task_title,
            "status": status,
            "details": details or {},
        }
    )


def advance_execution_state(state: dict[str, Any]) -> dict[str, Any]:
    updated_state = json.loads(json.dumps(state))
    phases = updated_state.get("phase_summary", [])
    current_time = datetime.now(timezone.utc).isoformat()

    in_progress_index = next(
        (index for index, phase in enumerate(phases) if phase.get("status") == "in_progress"),
        None,
    )

    if in_progress_index is not None:
        for task in phases[in_progress_index].get("task_status", []):
            if task.get("status") != "completed":
                task["status"] = "completed"
                task["last_updated"] = current_time
        phases[in_progress_index]["status"] = "completed"
        updated_state["history"].append(
            {
                "phase": phases[in_progress_index]["name"],
                "action": "completed",
                "timestamp": current_time,
            }
        )
        append_audit_event(
            updated_state,
            event_type="phase_transition",
            phase_name=phases[in_progress_index]["name"],
            status="completed",
            details={"mode": "advance_phase"},
        )
        next_index = in_progress_index + 1
        if next_index < len(phases):
            phases[next_index]["status"] = "ready"
            updated_state["history"].append(
                {
                    "phase": phases[next_index]["name"],
                    "action": "unblocked",
                    "timestamp": current_time,
                }
            )
            append_audit_event(
                updated_state,
                event_type="phase_transition",
                phase_name=phases[next_index]["name"],
                status="ready",
                details={"reason": "previous phase completed"},
            )
        updated_state["last_action"] = f"completed {phases[in_progress_index]['name']}"
    else:
        ready_index = next(
            (index for index, phase in enumerate(phases) if phase.get("status") == "ready"),
            None,
        )
        if ready_index is None:
            updated_state["last_action"] = "no-op"
        else:
            phases[ready_index]["status"] = "in_progress"
            updated_state["history"].append(
                {
                    "phase": phases[ready_index]["name"],
                    "action": "started",
                    "timestamp": current_time,
                }
            )
            append_audit_event(
                updated_state,
                event_type="phase_transition",
                phase_name=phases[ready_index]["name"],
                status="in_progress",
                details={"mode": "advance_phase"},
            )
            updated_state["last_action"] = f"started {phases[ready_index]['name']}"

    updated_state["last_updated"] = current_time
    return updated_state


def render_task_evidence(
    phase_name: str,
    task_title: str,
    task_id: str,
    project_root: Path,
    changed_files: list[str] | None = None,
) -> str:
    file_lines = "\n".join(f"- {item}" for item in (changed_files or []))
    return (
        f"# Evidence {task_id}\n\n"
        f"- Phase: {phase_name}\n"
        f"- Task: {task_title}\n"
        f"- Result: completed\n"
        f"- Project root: {project_root}\n"
        f"- Changed files:\n{file_lines or '- none'}\n"
    )


def write_file_if_changed(path: Path, content: str) -> str:
    normalized = content.rstrip() + "\n"
    existed_before = path.exists()
    if path.exists() and path.read_text(encoding="utf-8") == normalized:
        return "unchanged"
    write_file(path, normalized)
    if existed_before:
        return "updated"
    return "created"


def render_constraint_resolution(spec: dict[str, Any]) -> str:
    constraints = json.dumps(spec.get("constraints", {}), indent=2, ensure_ascii=True)
    assumptions = "\n".join(f"- {item}" for item in spec.get("assumptions", []))
    return (
        "# Constraint Resolution\n\n"
        "## Constraints\n\n"
        "```json\n"
        f"{constraints}\n"
        "```\n\n"
        "## Assumptions\n\n"
        f"{assumptions or '- none'}\n"
    )


def render_api_contract(spec: dict[str, Any]) -> str:
    domain = spec.get("domain", "generic_web_application")
    if domain == "academic_management":
        endpoints = [
            "GET /health",
            "GET /students",
            "POST /students",
            "GET /courses",
            "POST /enrollments",
            "GET /reports/transcripts/{student_id}",
        ]
    else:
        endpoints = [
            "GET /health",
            "GET /resources",
            "POST /resources",
            "GET /audit-events",
        ]

    endpoint_lines = "\n".join(f"- {item}" for item in endpoints)
    return (
        "# API Contract Baseline\n\n"
        "Generated by execution handler for architecture baseline tasks.\n\n"
        "## Endpoints\n\n"
        f"{endpoint_lines}\n"
    )


def render_generated_ci_workflow() -> str:
    return (
        "name: generated-project-ci\n\n"
        "on:\n"
        "  push:\n"
        "    branches: [ \"main\" ]\n"
        "  pull_request:\n"
        "    branches: [ \"main\" ]\n\n"
        "jobs:\n"
        "  quality:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - name: Setup Python\n"
        "        uses: actions/setup-python@v5\n"
        "        with:\n"
        "          python-version: '3.11'\n"
        "      - name: Syntax check\n"
        "        run: python -m compileall scaffold/backend/app\n"
        "      - name: Smoke import\n"
        "        run: python -c \"import pathlib; print(pathlib.Path('scaffold/backend/app/main.py').exists())\"\n"
    )


def render_module_stub(module_name: str) -> str:
    class_name = "".join(part.capitalize() for part in module_name.split("_")) or "Module"
    return (
        f"\"\"\"Generated module scaffold for {module_name}.\"\"\"\n\n"
        f"class {class_name}Service:\n"
        "    def run(self) -> dict[str, str]:\n"
        f"        return {{\"module\": \"{module_name}\", \"status\": \"initialized\"}}\n"
    )


def apply_task_handler(
    project_root: Path,
    state: dict[str, Any],
    phase_name: str,
    task_title: str,
) -> dict[str, Any]:
    spec = state.get("spec_snapshot", {})
    file_changes: dict[str, str] = {}
    backup_contents: dict[str, str] = {}

    def write_and_track(relative_path: str, content: str) -> None:
        path = project_root / relative_path
        previous_content = path.read_text(encoding="utf-8") if path.exists() else None
        change_result = write_file_if_changed(path, content)
        if change_result in {"created", "updated"}:
            file_changes[relative_path] = change_result
        if change_result == "updated" and previous_content is not None:
            backup_contents[relative_path] = previous_content

    if task_title == "Validate goal against domain ontology":
        payload = {
            "goal": state.get("goal"),
            "domain": state.get("domain"),
            "result": "compatible",
            "validated_at": datetime.now(timezone.utc).isoformat(),
        }
        write_and_track(
            "execution/validation/domain-check.json",
            json.dumps(payload, indent=2, ensure_ascii=True),
        )
    elif task_title == "Resolve missing constraints and assumptions":
        write_and_track(
            "planning/constraint-resolution.md",
            render_constraint_resolution(spec),
        )
    elif task_title == "Freeze machine-readable specification":
        write_and_track(
            "spec/requirements.lock.json",
            json.dumps(spec, indent=2, ensure_ascii=True),
        )
    elif task_title.startswith("Adopt architecture style:"):
        architecture = state.get("selected_architecture", {})
        notes = [
            "# Architecture Implementation Notes",
            "",
            f"- Selected style: {architecture.get('style', 'unknown')}",
            f"- Backend: {architecture.get('backend', 'unknown')}",
            f"- Database: {architecture.get('database', 'unknown')}",
            f"- Deployment: {architecture.get('deployment', 'unknown')}",
        ]
        write_and_track("architecture/implementation-notes.md", "\n".join(notes))
    elif task_title == "Define API contract and database schema":
        write_and_track("planning/api-contract.md", render_api_contract(spec))
    elif task_title == "Set CI quality gates":
        write_and_track(".github/workflows/ci-generated.yml", render_generated_ci_workflow())
    elif task_title.startswith("Implement module: "):
        module_name = task_title.removeprefix("Implement module: ").strip()
        module_slug = slugify(module_name).replace("-", "_")
        write_and_track(
            f"scaffold/backend/app/modules/{module_slug}.py",
            render_module_stub(module_slug),
        )
    elif task_title == "Run integration scenarios":
        write_and_track(
            "execution/reports/integration-checklist.md",
            "# Integration Scenarios\n\n- [ ] End-to-end enrollment flow\n- [ ] Grade publishing flow\n- [ ] Attendance alert flow\n",
        )
    elif task_title == "Validate security controls":
        write_and_track(
            "execution/reports/security-checklist.md",
            "# Security Controls\n\n- [ ] RBAC validation\n- [ ] Audit log integrity\n- [ ] Input validation checks\n",
        )
    elif task_title == "Execute rollback drill in staging":
        write_and_track(
            "execution/reports/rollback-drill.md",
            "# Rollback Drill\n\n- [ ] Simulate failed deployment\n- [ ] Restore previous artifact\n- [ ] Validate post-rollback health\n",
        )

    return {
        "file_changes": file_changes,
        "backup_contents": backup_contents,
    }


def remove_file_and_empty_parents(path: Path, stop_at: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    path.unlink()

    current = path.parent
    while current != stop_at and current.exists():
        try:
            current.rmdir()
        except OSError:
            break
        current = current.parent
    return True


def rollback_last_task(project_root: Path, state: dict[str, Any]) -> dict[str, Any]:
    updated_state = json.loads(json.dumps(state))
    phases = updated_state.get("phase_summary", [])
    rolled_back_event_ids = updated_state.setdefault("rolled_back_event_ids", [])
    now = datetime.now(timezone.utc).isoformat()

    last_task_event = next(
        (
            event
            for event in reversed(updated_state.get("audit_trail", []))
            if event.get("event_type") == "task_execution"
            and event.get("status") == "completed"
            and event.get("id") not in rolled_back_event_ids
        ),
        None,
    )

    if last_task_event is None:
        updated_state["last_action"] = "rollback no-op (no completed task found)"
        updated_state["last_updated"] = now
        append_audit_event(
            updated_state,
            event_type="rollback",
            phase_name="none",
            status="no-op",
            details={"reason": "no completed task in audit trail"},
        )
        return updated_state

    phase_name = str(last_task_event.get("phase", ""))
    task_title = str(last_task_event.get("task", ""))
    details = last_task_event.get("details", {}) or {}
    file_changes = details.get("file_changes", {}) or {}
    backup_contents = details.get("backup_contents", {}) or {}

    reverted_files: list[str] = []
    non_reverted_files: list[str] = []
    removed_evidence = False

    for relative_path, change_type in file_changes.items():
        if change_type == "created":
            removed = remove_file_and_empty_parents(project_root / relative_path, project_root)
            if removed:
                reverted_files.append(relative_path)
            else:
                non_reverted_files.append(relative_path)
            continue

        if change_type == "updated" and relative_path in backup_contents:
            write_file(project_root / relative_path, str(backup_contents[relative_path]))
            reverted_files.append(relative_path)
            continue

        non_reverted_files.append(relative_path)

    for phase_index, phase in enumerate(phases):
        if phase.get("name") != phase_name:
            continue

        for task in phase.get("task_status", []):
            if task.get("title") != task_title:
                continue
            task["status"] = "pending"
            task["last_updated"] = now

            evidence_file = task.get("evidence_file")
            if evidence_file:
                removed_evidence = remove_file_and_empty_parents(
                    project_root / evidence_file,
                    project_root,
                )
            break

        phase["status"] = "in_progress"
        next_index = phase_index + 1
        if next_index < len(phases) and phases[next_index].get("status") == "ready":
            phases[next_index]["status"] = "pending"
        break

    updated_state["history"].append(
        {
            "phase": phase_name,
            "action": "rolled_back_last_task",
            "timestamp": now,
        }
    )
    append_audit_event(
        updated_state,
        event_type="rollback",
        phase_name=phase_name,
        task_title=task_title,
        status="completed",
        details={
            "reverted_files": reverted_files,
            "non_reverted_files": non_reverted_files,
            "removed_evidence": removed_evidence,
            "source_event_id": last_task_event.get("id"),
        },
    )
    if last_task_event.get("id") is not None:
        rolled_back_event_ids.append(last_task_event["id"])
    updated_state["last_action"] = f"rolled back task '{task_title}' in {phase_name}"
    updated_state["last_error"] = None
    updated_state["last_updated"] = now
    return updated_state


def execute_phase_actions(
    project_root: Path,
    state: dict[str, Any],
    dry_run_actions: bool = False,
) -> dict[str, Any]:
    updated_state = json.loads(json.dumps(state))
    phases = updated_state.get("phase_summary", [])
    now = datetime.now(timezone.utc).isoformat()

    active_phase_index = next(
        (index for index, phase in enumerate(phases) if phase.get("status") == "in_progress"),
        None,
    )
    if active_phase_index is None:
        active_phase_index = next(
            (index for index, phase in enumerate(phases) if phase.get("status") == "ready"),
            None,
        )
        if active_phase_index is None:
            updated_state["last_action"] = "no-op"
            updated_state["last_updated"] = now
            append_audit_event(
                updated_state,
                event_type="execution",
                phase_name="none",
                status="no-op",
                details={"reason": "no ready or in_progress phase"},
            )
            return updated_state

        phases[active_phase_index]["status"] = "in_progress"
        updated_state["history"].append(
            {
                "phase": phases[active_phase_index]["name"],
                "action": "started",
                "timestamp": now,
            }
        )
        append_audit_event(
            updated_state,
            event_type="phase_transition",
            phase_name=phases[active_phase_index]["name"],
            status="in_progress",
            details={"mode": "execute_phase"},
        )

    active_phase = phases[active_phase_index]
    executed_count = 0
    skipped_count = 0

    try:
        for task in active_phase.get("task_status", []):
            if task.get("status") == "completed":
                skipped_count += 1
                append_audit_event(
                    updated_state,
                    event_type="task_execution",
                    phase_name=active_phase["name"],
                    task_title=task["title"],
                    status="skipped_already_completed",
                    details={"task_id": task["id"]},
                )
                continue

            evidence_relative_path = Path(task["evidence_file"])
            evidence_path = project_root / evidence_relative_path

            if dry_run_actions:
                append_audit_event(
                    updated_state,
                    event_type="task_execution",
                    phase_name=active_phase["name"],
                    task_title=task["title"],
                    status="planned",
                    details={
                        "task_id": task["id"],
                        "evidence_file": str(evidence_relative_path),
                    },
                )
                continue

            handler_result = apply_task_handler(
                project_root,
                updated_state,
                active_phase["name"],
                task["title"],
            )
            file_changes = handler_result["file_changes"]
            backup_contents = handler_result["backup_contents"]
            changed_files = sorted(file_changes)
            write_file(
                evidence_path,
                render_task_evidence(
                    active_phase["name"],
                    task["title"],
                    task["id"],
                    project_root,
                    changed_files,
                ),
            )
            task["status"] = "completed"
            task["last_updated"] = now
            executed_count += 1
            append_audit_event(
                updated_state,
                event_type="task_execution",
                phase_name=active_phase["name"],
                task_title=task["title"],
                status="completed",
                details={
                    "task_id": task["id"],
                    "evidence_file": str(evidence_relative_path),
                    "changed_files": changed_files,
                    "file_changes": file_changes,
                    "backup_contents": backup_contents,
                },
            )

        all_tasks_completed = all(
            task.get("status") == "completed"
            for task in active_phase.get("task_status", [])
        )
        if all_tasks_completed and not dry_run_actions:
            active_phase["status"] = "completed"
            updated_state["history"].append(
                {
                    "phase": active_phase["name"],
                    "action": "completed",
                    "timestamp": now,
                }
            )
            append_audit_event(
                updated_state,
                event_type="phase_transition",
                phase_name=active_phase["name"],
                status="completed",
                details={"mode": "execute_phase"},
            )

            next_index = active_phase_index + 1
            if next_index < len(phases):
                phases[next_index]["status"] = "ready"
                updated_state["history"].append(
                    {
                        "phase": phases[next_index]["name"],
                        "action": "unblocked",
                        "timestamp": now,
                    }
                )
                append_audit_event(
                    updated_state,
                    event_type="phase_transition",
                    phase_name=phases[next_index]["name"],
                    status="ready",
                    details={"reason": "previous phase completed"},
                )

        if dry_run_actions:
            updated_state["last_action"] = f"planned execution for {active_phase['name']}"
        else:
            updated_state["last_action"] = (
                f"executed {executed_count} tasks in {active_phase['name']}"
            )
        updated_state["last_error"] = None
    except OSError as exc:
        updated_state["last_error"] = str(exc)
        updated_state["last_action"] = f"failed execution in {active_phase['name']}"
        append_audit_event(
            updated_state,
            event_type="execution",
            phase_name=active_phase["name"],
            status="failed",
            details={"error": str(exc)},
        )

    updated_state["last_updated"] = now
    append_audit_event(
        updated_state,
        event_type="execution",
        phase_name=active_phase["name"],
        status="dry-run" if dry_run_actions else "completed",
        details={
            "executed_tasks": executed_count,
            "skipped_tasks": skipped_count,
            "dry_run_actions": dry_run_actions,
        },
    )
    return updated_state


def render_execution_state(state: dict[str, Any]) -> str:
    lines: list[str] = ["# Execution State", ""]
    lines.append(f"Goal: {state['goal']}")
    lines.append(f"Domain: {state['domain']}")
    lines.append(f"Last action: {state['last_action']}")
    lines.append(f"Last error: {state.get('last_error') or 'none'}")
    lines.append("")
    lines.append("## Phases")
    lines.append("")
    for phase in state.get("phase_summary", []):
        lines.append(f"### {phase['order']}. {phase['name']}")
        lines.append(f"- Status: {phase['status']}")
        lines.append("- Task status:")
        for task in phase.get("task_status", []):
            lines.append(f"  - {task['id']}: {task['status']} ({task['title']})")
        lines.append("")
    lines.append("## Recent Audit")
    lines.append("")
    for event in state.get("audit_trail", [])[-10:]:
        event_task = event.get("task") or "-"
        lines.append(
            f"- {event['timestamp']} | {event['event_type']} | {event['phase']} | {event_task} | {event['status']}"
        )
    return "\n".join(lines)


def load_execution_state(state_path: Path) -> dict[str, Any] | None:
    if not state_path.exists():
        return None
    return json.loads(state_path.read_text(encoding="utf-8"))


def render_execution_runbook(execution_report: dict[str, Any]) -> str:
    lines: list[str] = ["# Execution Runbook", ""]
    lines.append(f"Goal: {execution_report['goal']}")
    lines.append(f"Domain: {execution_report['domain']}")
    lines.append("")
    lines.append("## Phase Status")
    lines.append("")
    for phase in execution_report["phase_summary"]:
        lines.append(f"### {phase['order']}. {phase['name']}")
        lines.append(f"- Status: {phase['status']}")
        lines.append("- Tasks:")
        for task in phase["tasks"]:
            lines.append(f"  - {task}")
        lines.append("- Exit criteria:")
        for criterion in phase["exit_criteria"]:
            lines.append(f"  - {criterion}")
        lines.append("")
    lines.append("## Next Action")
    lines.append("")
    lines.append(execution_report["next_action"])
    return "\n".join(lines)


def render_decision_log(decision_log: dict[str, Any]) -> str:
    lines: list[str] = ["# Decision Log", ""]
    lines.append(f"Goal: {decision_log['goal']}")
    lines.append(f"Domain: {decision_log['domain']}")
    lines.append(f"Project name: {decision_log['project_name']}")
    lines.append("")
    lines.append("## Entries")
    lines.append("")
    for entry in decision_log.get("entries", []):
        note = f" ({entry['note']})" if entry.get("note") else ""
        lines.append(
            f"- {entry['index']}. {entry['key']} = {entry['value']} [{entry['source']}]" + note
        )
    lines.append("")
    lines.append("## Final Constraints")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(decision_log.get("constraints", {}), indent=2, ensure_ascii=True))
    lines.append("```")
    return "\n".join(lines)


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def render_adr(architecture: dict[str, Any]) -> str:
    rationale = "\n".join(f"- {item}" for item in architecture["rationale"])
    return f"""# ADR-0001 Initial Architecture

## Context
Initial autonomous planning run.

## Decision
- Style: {architecture['style']}
- Backend: {architecture['backend']}
- Frontend: {architecture['frontend']}
- Database: {architecture['database']}
- Deployment: {architecture['deployment']}
- Cloud target: {architecture['cloud']}

## Rationale
{rationale}

## Consequences
- Enables deterministic phased delivery.
- Keeps decision records explicit for later autonomous revisions.
"""


def render_execution_plan(backlog: list[dict[str, Any]]) -> str:
    lines: list[str] = ["# Execution Plan", ""]
    for index, phase in enumerate(backlog, start=1):
        lines.append(f"## {index}. {phase['phase']}")
        lines.append("")
        lines.append("### Tasks")
        for task in phase["tasks"]:
            lines.append(f"- {task}")
        lines.append("")
        lines.append("### Exit Criteria")
        for item in phase["exit_criteria"]:
            lines.append(f"- {item}")
        lines.append("")
    return "\n".join(lines)


def render_scaffold_readme(project_name: str, domain: str) -> str:
    schema_label = "domain-aligned SQL schema" if domain != "academic_management" else "Initial SQL schema for academic entities"
    return f"""# {project_name} Scaffold

This scaffold is generated by autonomous_factory/factory.py.

## Included
- Minimal backend health endpoint
- {schema_label}
- Basic Bootstrap frontend placeholder

## Run backend
```bash
cd scaffold/backend/app
python3 main.py
```

Backend health check:
```bash
curl http://127.0.0.1:8000/health
```
"""


def render_backend_main(service_name: str) -> str:
    return f"""from http.server import BaseHTTPRequestHandler, HTTPServer
import json


class Handler(BaseHTTPRequestHandler):
    def _write_json(self, status_code, payload):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status_code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path == "/health":
            self._write_json(200, {{"status": "ok", "service": "{service_name}"}})
            return
        self._write_json(404, {{"error": "not_found"}})


def main():
    server = HTTPServer(("127.0.0.1", 8000), Handler)
    print("Serving on http://127.0.0.1:8000")
    server.serve_forever()


if __name__ == "__main__":
    main()
"""


def render_schema_sql(spec: dict[str, Any]) -> str:
    if spec.get("domain") == "academic_management":
        return """CREATE TABLE students (
    id SERIAL PRIMARY KEY,
    registration_number VARCHAR(32) UNIQUE NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE professors (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE courses (
    id SERIAL PRIMARY KEY,
    code VARCHAR(32) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    workload_hours INTEGER NOT NULL CHECK (workload_hours > 0)
);

CREATE TABLE enrollments (
    id SERIAL PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id),
    course_id INTEGER NOT NULL REFERENCES courses(id),
    status VARCHAR(32) NOT NULL,
    enrolled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (student_id, course_id)
);
"""

    return """CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE resources (
    id SERIAL PRIMARY KEY,
    owner_id INTEGER NOT NULL REFERENCES users(id),
    title VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_events (
    id SERIAL PRIMARY KEY,
    actor_id INTEGER REFERENCES users(id),
    event_type VARCHAR(64) NOT NULL,
    payload JSON NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""


def render_frontend_html(project_name: str, domain: str) -> str:
    if domain == "academic_management":
        badges = """
                            <span class="badge text-bg-primary">Students</span>
                            <span class="badge text-bg-success">Courses</span>
                            <span class="badge text-bg-warning">Enrollments</span>
                            <span class="badge text-bg-info">Reports</span>
"""
        subtitle = "Initial dashboard placeholder generated by the autonomous factory MVP."
    else:
        badges = """
                            <span class="badge text-bg-primary">Users</span>
                            <span class="badge text-bg-success">Resources</span>
                            <span class="badge text-bg-warning">Audit</span>
                            <span class="badge text-bg-info">Metrics</span>
"""
        subtitle = "Initial dashboard placeholder generated for the selected domain."

    return f"""<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{project_name} - Bootstrap</title>
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
        crossorigin="anonymous"
    />
</head>
<body class="bg-light">
    <main class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="card shadow-sm border-0">
                    <div class="card-body p-4 p-md-5">
                        <h1 class="h3 mb-3">{project_name}</h1>
                        <p class="text-secondary mb-4">
                            {subtitle}
                        </p>
                        <div class="d-flex gap-2 flex-wrap">{badges}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</body>
</html>
"""


def render_root_readme(project_name: str, spec: dict[str, Any]) -> str:
    constraints = spec.get("constraints", {})
    pretty_constraints = json.dumps(constraints, indent=2, ensure_ascii=True)
    return f"""# {project_name}

Generated by `autonomous_factory/factory.py`.

## Goal
{spec['goal']}

## Domain
{spec['domain']}

## Constraints
```json
{pretty_constraints}
```

## Generated Artifacts
- `spec/requirements.json`
- `planning/intent-contract.json`
- `architecture/adr-0001-initial-architecture.md`
- `planning/backlog.json`
- `planning/execution-plan.md`
- `governance/release-gates.md`
- `scaffold/`
"""


def build_intent_contract(
    goal: str,
    domain: str,
    project_name: str,
    constraints: dict[str, Any],
    spec: dict[str, Any],
    architecture: dict[str, Any],
    backlog: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "goal": goal,
        "domain": domain,
        "project_name": project_name,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "constraints": constraints,
        "assumptions": spec.get("assumptions", []),
        "entities": spec.get("entities", []),
        "modules": spec.get("modules", []),
        "workflows": spec.get("workflows", []),
        "non_functional": spec.get("non_functional", {}),
        "governance": spec.get("governance", {}),
        "architecture": architecture,
        "backlog": backlog,
        "acceptance_focus": {
            "primary_phase": backlog[0]["phase"] if backlog else None,
            "primary_exit_criteria": backlog[0]["exit_criteria"] if backlog else [],
        },
    }


def render_intent_contract(intent_contract: dict[str, Any]) -> str:
    return f"""# Intent Contract

## Goal
{intent_contract['goal']}

## Domain
{intent_contract['domain']}

## Project
{intent_contract['project_name']}

## Primary Phase
{intent_contract.get('acceptance_focus', {}).get('primary_phase', '-')}

## Architecture
- Style: {intent_contract['architecture'].get('style', '-')}
- Backend: {intent_contract['architecture'].get('backend', '-')}
- Frontend: {intent_contract['architecture'].get('frontend', '-')}
- Database: {intent_contract['architecture'].get('database', '-')}

## Modules
{chr(10).join(f'- {item}' for item in intent_contract.get('modules', []))}

## Workflows
{chr(10).join(f'- {item}' for item in intent_contract.get('workflows', []))}
"""


def write_project(
    root: Path,
    project_name: str,
    spec: dict[str, Any],
    architecture: dict[str, Any],
    backlog: list[dict[str, Any]],
    decision_log: dict[str, Any] | None = None,
    local_llm_advice: dict[str, Any] | None = None,
    execution_report: dict[str, Any] | None = None,
    execution_state: dict[str, Any] | None = None,
) -> None:
    intent_contract = build_intent_contract(
        spec["goal"],
        spec["domain"],
        project_name,
        spec.get("constraints", {}),
        spec,
        architecture,
        backlog,
    )

    write_file(root / "README.md", render_root_readme(project_name, spec))
    write_file(root / "spec/requirements.json", json.dumps(spec, indent=2, ensure_ascii=True))
    write_file(
        root / "planning/intent-contract.json",
        json.dumps(intent_contract, indent=2, ensure_ascii=True),
    )
    write_file(
        root / "planning/intent-contract.md",
        render_intent_contract(intent_contract),
    )
    write_file(
        root / "architecture/adr-0001-initial-architecture.md",
        render_adr(architecture),
    )
    write_file(root / "planning/backlog.json", json.dumps(backlog, indent=2, ensure_ascii=True))
    write_file(root / "planning/execution-plan.md", render_execution_plan(backlog))

    if decision_log is not None:
        write_file(
            root / "planning/decision-log.json",
            json.dumps(decision_log, indent=2, ensure_ascii=True),
        )
        write_file(
            root / "planning/decision-log.md",
            render_decision_log(decision_log),
        )
        integrity = decision_log.get("integrity", {})
        decision_hash = integrity.get("hash")
        if isinstance(decision_hash, str) and decision_hash:
            write_file(
                root / "planning/decision-log.sha256",
                f"{decision_hash}  decision-log.json",
            )

    if local_llm_advice is not None:
        write_file(
            root / "analysis/local-llm-advice.json",
            json.dumps(local_llm_advice, indent=2, ensure_ascii=True),
        )
        write_file(
            root / "analysis/local-llm-advice.md",
            render_local_llm_advice(local_llm_advice),
        )

        local_llm_focus = derive_local_llm_focus(local_llm_advice, spec)
        write_file(
            root / "execution/ai-focus.json",
            json.dumps(local_llm_focus, indent=2, ensure_ascii=True),
        )
        write_file(
            root / "execution/ai-focus.md",
            render_local_llm_focus(local_llm_focus),
        )

    release_gates = spec["governance"]["approval_gates"]
    gates_markdown = "\n".join(f"- {gate}" for gate in release_gates)
    write_file(
        root / "governance/release-gates.md",
        "# Release Gates\n\n" + gates_markdown,
    )

    write_file(root / "scaffold/README.md", render_scaffold_readme(project_name, spec['domain']))
    write_file(root / "scaffold/backend/app/main.py", render_backend_main(f"{project_name}-backend"))
    write_file(root / "scaffold/database/schema.sql", render_schema_sql(spec))
    write_file(root / "scaffold/frontend/index.html", render_frontend_html(project_name, spec['domain']))

    if execution_report is not None:
        write_file(
            root / "execution/report.json",
            json.dumps(execution_report, indent=2, ensure_ascii=True),
        )
        write_file(
            root / "execution/runbook.md",
            render_execution_runbook(execution_report),
        )

    if execution_state is not None:
        write_file(
            root / "execution/state.json",
            json.dumps(execution_state, indent=2, ensure_ascii=True),
        )
        write_file(
            root / "execution/state.md",
            render_execution_state(execution_state),
        )
        write_file(
            root / "execution/audit-trail.json",
            json.dumps(execution_state.get("audit_trail", []), indent=2, ensure_ascii=True),
        )


def main() -> int:
    args = parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    if ensure_local_llm_config(repo_root):
        print("Auto-created config/local_llm.json using hardware recommendation.")

    if args.advance_phase and args.execute_phase:
        print(
            "error: --advance-phase and --execute-phase cannot be used together.",
            file=sys.stderr,
        )
        return 2
    if args.verify_decision_log and (
        args.advance_phase
        or args.execute_phase
        or args.rollback_last_task
        or args.dry_run_execution
        or args.interactive
    ):
        print(
            "error: --verify-decision-log cannot be combined with generation/execution flags.",
            file=sys.stderr,
        )
        return 2
    if args.rollback_last_task and (args.advance_phase or args.execute_phase):
        print(
            "error: --rollback-last-task cannot be combined with --advance-phase or --execute-phase.",
            file=sys.stderr,
        )
        return 2
    if args.dry_run_actions and not args.execute_phase:
        print(
            "error: --dry-run-actions requires --execute-phase.",
            file=sys.stderr,
        )
        return 2

    try:
        constraints = parse_constraints(args.constraint)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    domain = infer_domain(args.goal)
    project_name = args.project_name or slugify(args.goal)
    decision_entries: list[dict[str, Any]] = []
    append_decision(decision_entries, key="goal", value=args.goal, source="input")
    append_decision(
        decision_entries,
        key="domain",
        value=domain,
        source="inference",
        note="Inferred from goal keywords.",
    )
    append_decision(
        decision_entries,
        key="project_name",
        value=project_name,
        source="cli" if args.project_name else "derived",
    )
    for key, value in sorted(constraints.items()):
        append_decision(decision_entries, key=key, value=value, source="cli")

    if args.interactive:
        project_name = prompt_project_name_interactively(project_name, decision_entries)
        constraints = collect_constraints_interactively(
            constraints,
            domain,
            decision_entries,
        )
        print("Resolved constraints:")
        print(json.dumps(constraints, indent=2, ensure_ascii=True))

    decision_log = build_decision_log(
        args.goal,
        domain,
        project_name,
        constraints,
        decision_entries,
    )
    decision_log_hash = compute_decision_log_hash(decision_log)
    decision_log["integrity"] = {
        "algorithm": "sha256",
        "hash": decision_log_hash,
        "artifact": "planning/decision-log.json",
    }

    output_root = Path(args.output).expanduser().resolve()
    destination = output_root / project_name

    if args.verify_decision_log:
        if not destination.exists():
            print(
                f"error: destination '{destination}' does not exist for verification.",
                file=sys.stderr,
            )
            return 2
        verified, message = verify_decision_log_integrity(destination)
        if verified:
            print(f"OK: {message}")
            return 0
        print(f"error: {message}", file=sys.stderr)
        return 1

    if destination.exists() and any(destination.iterdir()) and not args.force:
        print(
            f"error: destination '{destination}' already exists and is not empty. "
            "Use --force to overwrite.",
            file=sys.stderr,
        )
        return 2

    destination.mkdir(parents=True, exist_ok=True)

    spec = build_spec(args.goal, domain, constraints)
    architecture = choose_architecture(constraints, domain)
    backlog = build_backlog(spec, architecture)
    execution_report = (
        build_execution_report(spec, architecture, backlog)
        if args.dry_run_execution
        else None
    )
    local_llm_advice = generate_local_llm_advice(
        repo_root,
        goal=args.goal,
        domain=domain,
        project_name=project_name,
        architecture=architecture,
        spec=spec,
        decision_log=decision_log,
    )
    local_llm_focus = derive_local_llm_focus(local_llm_advice, spec)
    execution_state = None
    state_path = (
        Path(args.state_file).expanduser().resolve()
        if args.state_file
        else destination / "execution" / "state.json"
    )

    existing_state = load_execution_state(state_path)
    if args.rollback_last_task and existing_state is None:
        print(
            "error: cannot rollback because no execution state file was found.",
            file=sys.stderr,
        )
        return 2

    if existing_state is None:
        execution_state = build_execution_state(spec, architecture, backlog)
    else:
        execution_state = existing_state

    if args.advance_phase:
        execution_state = advance_execution_state(execution_state)
    elif args.execute_phase:
        execution_state = execute_phase_actions(
            destination,
            execution_state,
            dry_run_actions=args.dry_run_actions,
        )
    elif args.rollback_last_task:
        execution_state = rollback_last_task(destination, execution_state)
    else:
        execution_state["last_action"] = execution_state.get("last_action", "initialized")

    execution_state["decision_log_hash"] = decision_log_hash
    execution_state["decision_log_path"] = "planning/decision-log.json"
    execution_state["ai_focus"] = local_llm_focus
    execution_state["current_phase"] = local_llm_focus.get(
        "phase", execution_state.get("current_phase")
    )
    execution_state["current_task"] = local_llm_focus.get(
        "task_title", execution_state.get("current_task")
    )

    if not args.state_file:
        state_path = destination / "execution" / "state.json"

    write_project(
        destination,
        project_name,
        spec,
        architecture,
        backlog,
        decision_log,
        local_llm_advice,
        execution_report,
        execution_state,
    )

    print(f"Project generated at: {destination}")
    if execution_report is not None:
        print("Dry-run execution report generated at: execution/report.json")
    if execution_state is not None:
        print("Execution state written at: execution/state.json")
        if args.execute_phase:
            if args.dry_run_actions:
                print("Execution actions were planned only (dry-run).")
            else:
                print("Execution actions applied and evidence generated under execution/evidence/.")
        if args.rollback_last_task:
            print("Rollback processed using the last completed task from the audit trail.")
        print("Execution audit trail written at: execution/audit-trail.json")
    if local_llm_advice is not None:
        print("Local LLM advice written at: analysis/local-llm-advice.json")
        print("Local LLM focus written at: execution/ai-focus.json")
    print("Next step: inspect planning/execution-plan.md and start implementing phase P2.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
